default_platform(:ios)

platform :ios do
  desc "Build and upload iOS Safari extension to TestFlight"
  lane :store do
    build_app(
      scheme: "AboveVTT\ (iOS)",
      project: "AboveVTT.xcodeproj",
      export_method: "app-store",
      output_directory: "build"
    )
    upload_to_testflight
  end
end

platform :mac do
  desc "Build and upload macOS Safari extension to TestFlight"
  lane :store do
    build_app(
      scheme: "AboveVTT\ (macOS)",
      project: "AboveVTT.xcodeproj",
      export_method: "app-store",
      output_directory: "build"
    )
    upload_to_testflight
  end
end

platform :mac do
  desc "Build macOS app for local testing"
  lane :local do
    gym(
      scheme: "AboveVTT\ (macOS)",    
      clean: true,
      configuration: "Debug",
      export_method: "mac-application",
      output_directory: "./build",
    )
  end
end
