name: ios-release-build
run-name: ${{ github.actor }} is publishing a ${{ inputs.release_type }} build ${{ inputs.version_name_override }}

# This version (fastlane) requires these secrets in github:
# (or many are not particularly sensitive, so we could include in workflow)
##	APP_STORE_CONNECT_ISSUER_ID
##	APP_STORE_CONNECT_KEY_ID
##	APP_STORE_CONNECT_PRIVATE_KEY (Base64 encode your .p8 file)
##	FASTLANE_APPLE_ID
##	FASTLANE_TEAM_ID
##	FASTLANE_ITC_TEAM_ID
##	MATCH_PASSWORD (for certificate storage)
##	FASTLANE_SESSION (optional, if using manual authentication)
#
# TODO: Check if this requires any other pre-install of fastlane in project files
# TODO: Probably need to move the version numbers into the project files

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: "beta or production?"
        options:
          - beta
          - production
        default: prerelease
      version_name_override:
        description: "Version Name Override (Only specify this if you need a name outside of our typical naming convention)"
        required: false

jobs:
  build_with_signing:
    runs-on: macos-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          author_name: github.actor
          author_email: github

      - name: "Determine version_name"
        uses: ./github/actions/determine-version
        
      - name: "Build environment.js"
        uses: ./github/actions/build-environment
        
      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Install Fastlane
        run: gem install fastlane

      - name: Decode App Store Connect API Key
        run: |
          echo "${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}" | base64 --decode > AuthKey.p8

      - name: Build & Upload iOS to TestFlight
        env:
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
          FASTLANE_APPLE_ID: ${{ secrets.FASTLANE_APPLE_ID }}
          FASTLANE_TEAM_ID: ${{ secrets.FASTLANE_TEAM_ID }}
          FASTLANE_ITC_TEAM_ID: ${{ secrets.FASTLANE_ITC_TEAM_ID }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: cd safari && fastlane ios store

      - name: Build & Upload macOS to TestFlight
        env:
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
          FASTLANE_APPLE_ID: ${{ secrets.FASTLANE_APPLE_ID }}
          FASTLANE_TEAM_ID: ${{ secrets.FASTLANE_TEAM_ID }}
          FASTLANE_ITC_TEAM_ID: ${{ secrets.FASTLANE_ITC_TEAM_ID }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: cd safari && fastlane mac store
